### ISSUE TITLE
new char-buffer version

### ISSUE THREAD

**Issue by schnittstabil** [schnittstabil/caesar-salad#3]
bump to [v2.0.0](https://github.com/schnittstabil/char-buffer/releases/tag/v2.0.0).

**Comment by dlh2** [comment]
Hi again, I'm learning about npm too thanks to you, so... my request is:

Update dependencies from ^1.0.0 to ^2.0.0

https://github.com/schnittstabil/caesar-salad/blob/113be38b5ce26e6b13f8db52f41f946683c9ef92/package.json#L26-L28

Test it on: https://semver.npmjs.com/

Thanks 👍

**Comment by schnittstabil** [comment]
@dlh2 `^1.0.0||^2.0.0` works as expected :wink: ([https://travis-ci.org/schnittstabil/caesar-salad/builds/588564648](https://travis-ci.org/schnittstabil/caesar-salad/builds/588564648))
– `caesar-salad@v2.1.0` has been published.
